trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Checkout Source
- checkout: self
  displayName: Checkout Repository

# Check whether Terraform is already installed
- script: |
    if command -v terraform &> /dev/null
    then
        echo "Terraform is already installed."
        terraform version
    else
        echo "Terraform not found."
    fi
  displayName: Check Terraform Installation

# Install latest Terraform
- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: 'latest'

# Verify installation
- script: |
    terraform version
  displayName: Verify Terraform Installation

# Terraform Init
- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'online-user'
    backendAzureRmResourceGroupName: 'dana'
    backendAzureRmStorageAccountName: 'tfstatefilesa2026'
    backendAzureRmContainerName: 'demo'
    backendAzureRmKey: 'testing'

# Terraform Plan
- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out=tfplan'
    environmentServiceNameAzureRM: 'online-user'

# Terraform Apply
- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve -input=false tfplan'
    environmentServiceNameAzureRM: 'online-user'